CREATE TABLE Pacientes (
id int NOT NULL PRIMARY KEY,
nome varchar(255) NOT NULL,
sexo char(1),
estadocivil text,
email text,
endereco text,
nascimento text,
profissao text,
telefone text,
peso float,
altura float,
queixa text,
doencaatual text,
doencapre text,
doencaassoc text,
historia text,
habitos text,
medicacoes text,
estado text,
pa float,
fc float,
fr float, 
sp float,
observacao text
);
